USE lab_mysql;

CREATE TABLE IF NOT EXISTS
cars(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
car_vin VARCHAR(20) NOT NULL,
manufacturer VARCHAR(50) NOT NULL,
model VARCHAR(50) NOT NULL,
year INT(4),
colour VARCHAR(20));


CREATE TABLE IF NOT EXISTS
customers(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
customer_id INT(5) NOT NULL,
customer_name VARCHAR(50) NOT NULL,
phone_no VARCHAR(20),
email VARCHAR(50) DEFAULT '-',
address VARCHAR(100),
city VARCHAR(50),
state VARCHAR(50),
country VARCHAR(50),
postal INT(5));


CREATE TABLE IF NOT EXISTS
salesperson(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
staff_id VARCHAR(5) NOT NULL,
staff_name VARCHAR(100) NOT NULL,
store VARCHAR(50) NOT NULL);


CREATE TABLE IF NOT EXISTS
invoices(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
invoice_no VARCHAR(10) NOT NULL,
date VARCHAR(10) NOT NULL,
car INT NOT NULL,
customer INT NOT NULL,
sales_person INT NOT NULL);

